"""SkillKnowledgeConsolidator — offline skill knowledge graph.

The curator handles lifecycle (stale / archive / dedupe) over the
sidecar. This module is its quiet sibling: it walks the skill manifests
and emits a parallel, llm_wiki-compatible markdown tree under
``workspace/knowledge/wiki/`` so:

* future retrieval can find related skills via ``[[wikilinks]]`` without
  re-reading every ``SKILL.md``;
* the user can point the standalone ``llm_wiki`` desktop app at the
  ``knowledge/`` project to visualise the skill graph;
* the consolidator never edits a skill's authoritative ``SKILL.md`` —
  the wiki tree is a derived view, regenerated on a slow cadence.

Pure file I/O — **no LLM call, no embeddings**. Runs on a background
asyncio task (see :mod:`backend.skills.consolidator_service`) with a
warmup window and a 24h interval by default.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

import yaml
from loguru import logger

from .loader import SkillLoader, SkillManifest

_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n(.*)$", re.DOTALL)
_SLUG_RE = re.compile(r"[^a-z0-9]+")

_INDEX_HEADER = (
    "---\n"
    "type: index\n"
    "title: Skill Knowledge Index\n"
    "---\n\n"
    "# Skill Knowledge Index\n\n"
    "Auto-generated from `workspace/skills/`. Each skill maps to a"
    " concept page under `concepts/` carrying `[[wikilinks]]` to its"
    " declared related skills. Do not edit by hand — regenerated by the"
    " skill knowledge consolidator on its background tick.\n"
)

_LOG_HEADER = (
    "---\n"
    "type: log\n"
    "title: Skill Knowledge Log\n"
    "---\n\n"
    "# Skill Knowledge Log\n\n"
    "One line per consolidator run.\n\n"
)


@dataclass(slots=True)
class ConsolidationReport:
    """Counters returned by :meth:`SkillKnowledgeConsolidator.consolidate`."""

    started_at: str
    finished_at: str
    skills_processed: int
    pages_written: int
    pages_unchanged: int
    errors: List[str] = field(default_factory=list)


class SkillKnowledgeConsolidator:
    """Skills → ``wiki/`` knowledge tree with ``[[wikilinks]]`` graph.

    Output layout (mirrors llm_wiki's project schema)::

        <knowledge_dir>/
            wiki/
                index.md
                log.md
                concepts/<skill-slug>.md
                sources/skill-<skill-slug>.md

    ``concepts/<slug>.md`` carries the skill's description + triggers +
    related-skill wikilinks; ``sources/skill-<slug>.md`` is a thin
    pointer back to the authoritative ``SKILL.md`` so the knowledge
    side never duplicates the procedural content.
    """

    def __init__(
        self,
        loader: SkillLoader,
        knowledge_dir: Path,
        workspace_dir: Path,
        *,
        max_body_chars: int = 2000,
    ) -> None:
        self._loader = loader
        self._knowledge_dir = Path(knowledge_dir).resolve()
        self._workspace_dir = Path(workspace_dir).resolve()
        # Floor avoids accidentally truncating triggers/steps; ceiling
        # avoids dragging an oversized SKILL.md verbatim into the wiki.
        self._max_body_chars = max(500, int(max_body_chars))

    @property
    def wiki_dir(self) -> Path:
        return self._knowledge_dir / "wiki"

    # =====================================================================
    # Public API
    # =====================================================================

    def consolidate(self) -> ConsolidationReport:
        started = _utcnow_iso()
        errors: List[str] = []

        wiki = self.wiki_dir
        concepts_dir = wiki / "concepts"
        sources_dir = wiki / "sources"
        try:
            wiki.mkdir(parents=True, exist_ok=True)
            concepts_dir.mkdir(parents=True, exist_ok=True)
            sources_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            logger.warning("[knowledge] cannot create wiki tree: {}", exc)
            return ConsolidationReport(
                started_at=started,
                finished_at=_utcnow_iso(),
                skills_processed=0,
                pages_written=0,
                pages_unchanged=0,
                errors=[f"mkdir: {exc}"],
            )

        manifests = self._loader.load() or {}

        # Pre-compute slug map + meta cache so wikilinks resolve correctly
        # even when a skill references a peer that comes later in iteration.
        slug_map: Dict[str, str] = {}
        meta_cache: Dict[str, Dict[str, Any]] = {}
        for skill_id, manifest in manifests.items():
            slug_map[skill_id] = _slug(skill_id)
            meta_cache[skill_id] = self._extract_meta(manifest)

        processed = 0
        written = 0
        unchanged = 0

        for skill_id, manifest in manifests.items():
            processed += 1
            try:
                slug = slug_map[skill_id]
                concept_md = self._render_concept_page(
                    skill_id, manifest, meta_cache[skill_id], slug_map,
                )
                source_md = self._render_source_pointer(skill_id, manifest)
                if _write_if_changed(concepts_dir / f"{slug}.md", concept_md):
                    written += 1
                else:
                    unchanged += 1
                if _write_if_changed(sources_dir / f"skill-{slug}.md", source_md):
                    written += 1
                else:
                    unchanged += 1
            except Exception as exc:  # noqa: BLE001 — never let one skill kill the run
                errors.append(f"{skill_id}: {exc}")
                logger.warning(
                    "[knowledge] consolidate failed for {!r}: {}", skill_id, exc,
                )

        try:
            index_md = self._render_index(manifests, meta_cache, slug_map)
            if _write_if_changed(wiki / "index.md", index_md):
                written += 1
            else:
                unchanged += 1
        except Exception as exc:  # noqa: BLE001
            errors.append(f"index: {exc}")
            logger.warning("[knowledge] index render failed: {}", exc)

        finished = _utcnow_iso()
        try:
            self._append_log(
                wiki / "log.md",
                started=started,
                finished=finished,
                processed=processed,
                written=written,
                errors=errors,
            )
        except Exception as exc:  # noqa: BLE001
            logger.warning("[knowledge] log append failed: {}", exc)

        return ConsolidationReport(
            started_at=started,
            finished_at=finished,
            skills_processed=processed,
            pages_written=written,
            pages_unchanged=unchanged,
            errors=errors,
        )

    # =====================================================================
    # Rendering
    # =====================================================================

    def _render_concept_page(
        self,
        skill_id: str,
        manifest: SkillManifest,
        meta: Dict[str, Any],
        slug_map: Dict[str, str],
    ) -> str:
        title = manifest.name or skill_id
        description = (manifest.description or "").strip()
        triggers: List[str] = list(meta.get("triggers") or [])
        category: str = (
            str(meta.get("category") or "").strip() or "general"
        )
        tags: List[str] = list(manifest.tags or [])

        related_links: List[str] = []
        related_unresolved: List[str] = []
        for ref in meta.get("related_skills") or []:
            ref = str(ref).strip()
            if not ref or ref == skill_id:
                continue
            slug = slug_map.get(ref)
            if slug:
                related_links.append(slug)
            else:
                related_unresolved.append(ref)

        body = self._loader.read_body(skill_id) or ""
        excerpt = _excerpt(body, self._max_body_chars)
        source_ref = self._skill_source_ref(manifest)

        frontmatter = {
            "type": "concept",
            "title": title,
            "category": category,
            "tags": tags,
            "sources": [source_ref] if source_ref else [],
            "related": related_links,
        }
        fm_text = yaml.safe_dump(
            frontmatter, allow_unicode=True, sort_keys=False
        ).strip()

        lines: List[str] = ["---", fm_text, "---", "", f"# {title}", ""]
        if description:
            lines.extend([description, ""])

        if triggers:
            lines.extend(["## Triggers", ""])
            for trig in triggers:
                lines.append(f"- {trig}")
            lines.append("")

        if related_links or related_unresolved:
            lines.extend(["## Related", ""])
            for slug in related_links:
                lines.append(f"- [[{slug}]]")
            for ref in related_unresolved:
                lines.append(f"- {ref} (unresolved)")
            lines.append("")

        if excerpt:
            lines.extend(["## Summary", "", excerpt, ""])

        lines.extend(["## Source", "", f"- skill: `{skill_id}`"])
        if source_ref:
            lines.append(f"- path: `{source_ref}`")
        lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def _render_source_pointer(
        self,
        skill_id: str,
        manifest: SkillManifest,
    ) -> str:
        title = f"Source: skill {manifest.name or skill_id}"
        source_ref = self._skill_source_ref(manifest)
        frontmatter = {
            "type": "source",
            "title": title,
            "sources": [source_ref] if source_ref else [],
        }
        fm_text = yaml.safe_dump(
            frontmatter, allow_unicode=True, sort_keys=False
        ).strip()
        body = (
            f"Pointer page for skill `{skill_id}`. The authoritative"
            f" content lives in `{source_ref or 'skills/' + skill_id}`."
            f" Do not edit this file directly — it is regenerated by the"
            f" skill knowledge consolidator."
        )
        return f"---\n{fm_text}\n---\n\n# {title}\n\n{body}\n"

    def _render_index(
        self,
        manifests: Dict[str, SkillManifest],
        meta_cache: Dict[str, Dict[str, Any]],
        slug_map: Dict[str, str],
    ) -> str:
        groups: Dict[str, List[str]] = {}
        for skill_id in manifests:
            cat = (
                str(meta_cache[skill_id].get("category") or "").strip()
                or "general"
            )
            groups.setdefault(cat, []).append(skill_id)

        lines: List[str] = [_INDEX_HEADER.rstrip(), ""]
        for cat in sorted(groups):
            lines.extend([f"## {cat}", ""])
            for skill_id in sorted(groups[cat]):
                slug = slug_map[skill_id]
                desc = ""
                desc_raw = (manifests[skill_id].description or "").strip()
                if desc_raw:
                    desc = desc_raw.splitlines()[0].strip()
                if desc:
                    lines.append(f"- [[{slug}]] — {desc}")
                else:
                    lines.append(f"- [[{slug}]]")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def _append_log(
        self,
        path: Path,
        *,
        started: str,
        finished: str,
        processed: int,
        written: int,
        errors: List[str],
    ) -> None:
        if not path.exists():
            path.write_text(_LOG_HEADER, encoding="utf-8")
        line = (
            f"- {finished} consolidate: processed={processed}"
            f" written={written} errors={len(errors)}"
        )
        with path.open("a", encoding="utf-8") as fh:
            fh.write(line + "\n")

    # =====================================================================
    # Frontmatter parsing
    # =====================================================================

    def _extract_meta(self, manifest: SkillManifest) -> Dict[str, Any]:
        if manifest.body_path is None:
            return {}
        try:
            raw = manifest.body_path.read_text(encoding="utf-8")
        except OSError:
            return {}
        match = _FRONTMATTER_RE.match(raw)
        if not match:
            return {}
        try:
            data = yaml.safe_load(match.group(1)) or {}
        except yaml.YAMLError:
            return {}
        if not isinstance(data, dict):
            return {}

        zl: Dict[str, Any] = {}
        meta = data.get("metadata")
        if isinstance(meta, dict):
            inner = meta.get("lzagent") or meta.get("hermes")
            if isinstance(inner, dict):
                zl = inner

        triggers = zl.get("triggers") or data.get("triggers") or []
        if isinstance(triggers, str):
            triggers = [triggers]
        category = zl.get("category") or data.get("category") or ""
        related = zl.get("related_skills") or data.get("related_skills") or []
        if isinstance(related, str):
            related = [related]

        return {
            "triggers": [str(t).strip() for t in triggers if str(t).strip()],
            "category": str(category).strip(),
            "related_skills": [
                str(r).strip() for r in related if str(r).strip()
            ],
        }

    def _skill_source_ref(self, manifest: SkillManifest) -> str:
        if manifest.body_path is None:
            return ""
        try:
            rel = manifest.body_path.resolve().relative_to(self._workspace_dir)
            return rel.as_posix()
        except ValueError:
            return str(manifest.body_path).replace("\\", "/")
        except OSError:
            return ""


# =========================================================================
# Module-level helpers
# =========================================================================

def _slug(value: str) -> str:
    text = (value or "").strip().lower()
    text = _SLUG_RE.sub("-", text).strip("-")
    return text or "skill"


def _excerpt(body: str, max_chars: int) -> str:
    text = (body or "").strip()
    if not text:
        return ""
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 1].rstrip() + "…"


def _write_if_changed(path: Path, content: str) -> bool:
    """Write file only when content differs. Returns True when written."""
    try:
        existing = path.read_text(encoding="utf-8")
    except OSError:
        existing = None
    if existing == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _utcnow_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")
